replicaCount: 1
service:
  port: 80
ingress:
  enabled: true
  hosts:
    - host: dg-appeal-admin-web.youpin-k8s.net
      paths:
        - path: /
configMap:
  env:
    ENV_DEF:  VITE_API_BASE_URL VITE_IS_OPEN_MENU
    VITE_API_BASE_URL: http://dg-appeal-svc.youpin-k8s.net
    VITE_IS_OPEN_MENU: 1
resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
